
bridges = []
# to replace
persistence_dir = ''

[[agents]]
id = 'acorn-profiles-instance-agent'
# to replace
keystore_file = ''
name = 'Agent 1'
# to replace
public_address = ''
[[dnas]]
file = './dnas/profiles/dist/profiles.dna.json'
# to replace
hash = ''
id = 'acorn-profiles-dna'

[[instances]]
agent = 'acorn-profiles-instance-agent'
dna = 'acorn-profiles-dna'
id = 'acorn-profiles-instance'

[instances.storage]
type = 'lmdb'
# to replace
path = 'picklepath'

[[interfaces]]
admin = true
id = 'Acorn-interface'

[[interfaces.instances]]
id = 'acorn-profiles-instance'

[interfaces.driver]
port = 8889
type = 'websocket'

[logger]
state_dump = false
type = 'info'
[[logger.rules.rules]]
exclude = true
pattern = '^holochain_core::wasm_engine::api'
[[logger.rules.rules]]
exclude = true
pattern = '^holochain_core::nucleus::reducers::trace_return_hdk_function'
[[logger.rules.rules]]
exclude = true
pattern = '^ws'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
# last two digits of port here
# are a hidden reference to associated holochain/sim2h
# release number, e.g. 9044 = 0.0.44
sim2h_url = "ws://sim2h.harris-braun.com:9047/"

[[ui_bundles]]
hash = 'QmTT6oSPHNFn4x9ssBM14M1HznLVGjrFKCyBcsTyBudzfg'
id = 'dna-connections'
root_dir = './irrelevant'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'dna-connections'
dna_interface = 'Acorn-interface'
id = 'dna-connections-interface'
port = 3111
reroute_to_root = true

