
bridges = []
persistence_dir = '.'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
# to replace
keystore_file = ''
name = 'Agent 1'
# to replace
public_address = ''
[[dnas]]
file = './dna/acorn.dna.json'
# to replace
hash = ''
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'acorn'

[instances.storage]
type = 'lmdb'
# to replace
path = 'picklepath'

[[interfaces]]
admin = false
id = 'websocket-interface'

[[interfaces.instances]]
id = 'acorn'

[interfaces.driver]
port = 8889
type = 'websocket'

[logger]
state_dump = false
type = 'info'
[[logger.rules.rules]]
exclude = true
pattern = '^holochain_core::wasm_engine::api'
[[logger.rules.rules]]
exclude = true
pattern = '^holochain_core::nucleus::reducers::trace_return_hdk_function'
[[logger.rules.rules]]
exclude = true
pattern = '^ws'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false

[network]
type = "sim2h"
sim2h_url = "ws://192.168.0.44:9000/"
# sim2h_url = "ws://sim2h.harris-braun.com:9000/"
